import type { Project, Task, Employee, Finance } from "@shared/schema";

export const dummyProjects: (Project & { id: number })[] = [
  {
    id: 1,
    name: "Website Redesign",
    description: "Complete overhaul of the company website with modern design",
    status: "in-progress",
    client: "Acme Corporation",
    progress: 75,
    budget: "45000.00",
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-03-15"),
    createdAt: new Date("2024-01-10"),
  },
  {
    id: 2,
    name: "Mobile App Development",
    description: "iOS and Android app for customer engagement",
    status: "planning",
    client: "TechStart Inc.",
    progress: 25,
    budget: "80000.00",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-06-01"),
    createdAt: new Date("2024-01-20"),
  },
  {
    id: 3,
    name: "Brand Identity",
    description: "Logo and brand guidelines development",
    status: "completed",
    client: "Creative Studio",
    progress: 100,
    budget: "15000.00",
    startDate: new Date("2023-12-01"),
    endDate: new Date("2024-01-31"),
    createdAt: new Date("2023-11-25"),
  },
  {
    id: 4,
    name: "E-commerce Platform",
    description: "Custom e-commerce solution with payment integration",
    status: "on-hold",
    client: "Retail Pro",
    progress: 40,
    budget: "120000.00",
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-05-01"),
    createdAt: new Date("2023-12-15"),
  },
];

export const dummyTasks: (Task & { id: number; projectName?: string; assigneeName?: string })[] = [
  {
    id: 1,
    title: "Design homepage mockup",
    description: "Create initial homepage design concepts",
    status: "done",
    priority: "high",
    projectId: 1,
    projectName: "Website Redesign",
    assigneeId: 1,
    assigneeName: "Sarah Wilson",
    dueDate: new Date("2024-02-15"),
    createdAt: new Date("2024-01-15"),
  },
  {
    id: 2,
    title: "Implement user authentication",
    description: "Set up login and registration functionality",
    status: "in-progress",
    priority: "high",
    projectId: 2,
    projectName: "Mobile App Development",
    assigneeId: 2,
    assigneeName: "Mike Johnson",
    dueDate: new Date("2024-03-01"),
    createdAt: new Date("2024-02-01"),
  },
  {
    id: 3,
    title: "Database optimization",
    description: "Improve query performance and indexing",
    status: "todo",
    priority: "medium",
    projectId: 4,
    projectName: "E-commerce Platform",
    assigneeId: 3,
    assigneeName: "Alex Chen",
    dueDate: new Date("2024-02-28"),
    createdAt: new Date("2024-02-10"),
  },
  {
    id: 4,
    title: "Content management system",
    description: "Build CMS for easy content updates",
    status: "in-progress",
    priority: "medium",
    projectId: 1,
    projectName: "Website Redesign",
    assigneeId: 4,
    assigneeName: "Emma Davis",
    dueDate: new Date("2024-03-10"),
    createdAt: new Date("2024-02-05"),
  },
];

export const dummyEmployees: (Employee & { id: number })[] = [
  {
    id: 1,
    name: "Sarah Wilson",
    email: "sarah.wilson@company.com",
    role: "UI/UX Designer",
    department: "Design",
    avatar: "SW",
    phone: "+1 (555) 123-4567",
    hireDate: new Date("2023-03-15"),
    salary: "75000.00",
    isActive: true,
  },
  {
    id: 2,
    name: "Mike Johnson",
    email: "mike.johnson@company.com",
    role: "Senior Developer",
    department: "Engineering",
    avatar: "MJ",
    phone: "+1 (555) 234-5678",
    hireDate: new Date("2022-08-20"),
    salary: "95000.00",
    isActive: true,
  },
  {
    id: 3,
    name: "Alex Chen",
    email: "alex.chen@company.com",
    role: "Database Administrator",
    department: "Engineering",
    avatar: "AC",
    phone: "+1 (555) 345-6789",
    hireDate: new Date("2023-01-10"),
    salary: "85000.00",
    isActive: true,
  },
  {
    id: 4,
    name: "Emma Davis",
    email: "emma.davis@company.com",
    role: "Full Stack Developer",
    department: "Engineering",
    avatar: "ED",
    phone: "+1 (555) 456-7890",
    hireDate: new Date("2023-06-01"),
    salary: "88000.00",
    isActive: true,
  },
];

export const dummyFinances: (Finance & { id: number })[] = [
  {
    id: 1,
    type: "income",
    category: "Project Payment",
    description: "Website Redesign - Phase 1",
    amount: "22500.00",
    date: new Date("2024-02-01"),
    createdAt: new Date("2024-02-01"),
  },
  {
    id: 2,
    type: "expense",
    category: "Software License",
    description: "Adobe Creative Suite Annual License",
    amount: "2400.00",
    date: new Date("2024-01-15"),
    createdAt: new Date("2024-01-15"),
  },
  {
    id: 3,
    type: "income",
    category: "Consulting",
    description: "Brand Identity Consultation",
    amount: "5000.00",
    date: new Date("2024-01-30"),
    createdAt: new Date("2024-01-30"),
  },
  {
    id: 4,
    type: "expense",
    category: "Office Supplies",
    description: "Monthly office supplies and equipment",
    amount: "1200.00",
    date: new Date("2024-02-05"),
    createdAt: new Date("2024-02-05"),
  },
];

export const dashboardStats = {
  activeProjects: 24,
  pendingTasks: 142,
  teamMembers: 86,
  monthlyRevenue: "$84.2k",
};

export const revenueData = [
  { month: "Jan", revenue: 65000, expenses: 45000 },
  { month: "Feb", revenue: 72000, expenses: 48000 },
  { month: "Mar", revenue: 68000, expenses: 42000 },
  { month: "Apr", revenue: 84200, expenses: 52000 },
  { month: "May", revenue: 78000, expenses: 47000 },
  { month: "Jun", revenue: 92000, expenses: 55000 },
];

export const projectStatusData = [
  { status: "Completed", count: 12, color: "#10B981" },
  { status: "In Progress", count: 8, color: "#3B82F6" },
  { status: "On Hold", count: 3, color: "#F59E0B" },
  { status: "Delayed", count: 1, color: "#EF4444" },
];
